services:
  webui:
    build:
      context: ./webui
    container_name: lesson_webui
    restart: unless-stopped
    environment:
      - ENGINE_BASE_URL=http://engine:8080
    depends_on:
      - engine
    networks:
      - lesson_net

  caddy:
    build:
      context: ./caddy
    container_name: lesson_caddy
    restart: unless-stopped
    ports:
      - "${CADDY_BIND_IP:-0.0.0.0}:80:80"
      - "${CADDY_BIND_IP:-0.0.0.0}:443:443"
    environment:
      - LESSON_HOSTNAME=${LESSON_HOSTNAME:-}
      - ACME_EMAIL=${ACME_EMAIL:-}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}
      - TLS_MODE=${TLS_MODE:-dns}
      - MKCERT_CERT=/certs/localhost.pem
      - MKCERT_KEY=/certs/localhost-key.pem
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/certs:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - webui
    networks:
      - lesson_net

volumes:
  caddy_data:
  caddy_config:
